### ISSUE TITLE
Problems getting automatically expired

### ISSUE THREAD

**Issue by SiddheshwarKore** [360Performance/dynatrace-plugin-certcheck#12]
For URLs whose synthetic monitoring is in “Enabled” state.

- Since we set “Time interval for checks” as 24 hours, it checks and alert on every day  at “00:00” if the certificate is expiring in “Minimum Certificate Validity in Days”.
- Problems are creating on daily basis for all URLs if the certificate is expiring in “Minimum Certificate Validity in Days” and automatically getting closed after “10” minutes

For URLs whose synthetic monitoring is in “Disabled” state.

- It created problem only once for URLs if the certificate is expiring in “Minimum Certificate Validity in Days” and automatically getting closed after “10” minutes
- Its not creating problem on daily basis even  if the certificate is expiring in “Minimum Certificate Validity in Days”.

**Comment by reinhard-brandstaedter** [comment]
Please try the latest version (1.20).
There seems to have been a API change in Dynatrace (Problem title/source string length) that caused the symptoms in your description. This got fixed in 1.20.

**Comment by SiddheshwarKore** [comment]
It fixed the issue pertaining to autoexpiry after 10 minutes for sythetic monitoring enabled endpoints. For those where synthetic monitors have been disabled, it doesnt seem to create problems. Any idea, how this can be fixed?

**Comment by reinhard-brandstaedter** [comment]
@SiddheshwarKore release 1.30 also fixes the issue where Dynatrace doesn't allow to attach problems to disabled monitors that have been inactive for more than 24 hours.
