### ISSUE TITLE
Plugin execution on RHEL7 (or similar) fails due to dependency to newer glibc

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [360Performance/dynatrace-plugin-certcheck#18]
On older Linux OS (RHEL 7.x specifically) the plugin execution fails with errors like this:
```
Error(/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /apps/tapm/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so))
```
References: [Dynatrace community thread](https://community.dynatrace.com/t5/Extensions/Configuration-less-Advanced-SSL-Certificate-Check-Plugin/m-p/195895/highlight/true#M2439)

**Comment by PieterLuttig** [comment]
**ldd -r -v /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so**

Output:

 linux-vdso.so.1 =>  (0x00007ffc9ddac000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f2bcf442000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f2bcf074000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2bcfb6e000)


       Version information:
        /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so:
                libpthread.so.0 (GLIBC_2.2.5) => /usr/lib64/libpthread.so.0
                libc.so.6 (GLIBC_2.14) => /usr/lib64/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /usr/lib64/libc.so.6
                libc.so.6 (GLIBC_2.3) => /usr/lib64/libc.so.6
                libc.so.6 (GLIBC_2.25) => not found
                libc.so.6 (GLIBC_2.7) => /usr/lib64/libc.so.6
                libc.so.6 (GLIBC_2.17) => /usr/lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /usr/lib64/libc.so.6
        /usr/lib64/libpthread.so.0:
                ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.14) => /usr/lib64/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /usr/lib64/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /usr/lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /usr/lib64/libc.so.6
        /usr/lib64/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2

**yum info openssl**

Output:

Excluding 7 updates due to versionlock (use "yum versionlock status" to show them)
Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k
Release     : 25.el7_9
Size        : 814 k
Repo        : installed
From repo   : rhel-7-server-rpms
Summary     : Utilities from the general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.


yum versionlock status
Loaded plugins: aliases, auto-update-debuginfo, changelog, enabled_repos_upload, fastestmirror, filter-data, fs-snapshot, keys, langpacks, list-data, merge-conf,
              : package_upload, post-transaction-actions, priorities, product-id, protectbase, ps, remove-with-leaves, rpm-warm-cache, search-disabled-repos, show-
              : leaves, subscription-manager, tmprepo, tracer_upload, tsflags, upgrade-helper, verify, versionlock
Loading mirror speeds from cached hostfile
Investec_Bank_Limited_Beyond_Trust_PBIS_PBIS                                                                                                      | 1.7 kB  00:00:00
Investec_Bank_Limited_azure-cli_azure                                                                                                             | 2.1 kB  00:00:00
rhel-7-server-insights-3-rpms                                                                                                                     | 2.1 kB  00:00:00
rhel-7-server-rpms                                                                                                                                | 2.0 kB  00:00:00
0 packages excluded due to repository protections
0:samba-4.10.16-19.el7_9.*
0:libwbclient-4.10.16-19.el7_9.*
0:samba-client-libs-4.10.16-19.el7_9.*
0:samba-common-tools-4.10.16-19.el7_9.*
0:samba-common-4.10.16-19.el7_9.*
0:samba-common-libs-4.10.16-19.el7_9.*
0:samba-libs-4.10.16-19.el7_9.*
versionlock status done
Uploading Enabled Repositories Report
Loaded plugins: auto-update-debuginfo, fastestmirror, fs-snapshot, langpacks,
              : post-transaction-actions, priorities, product-id, protectbase,
              : remove-with-leaves, rpm-warm-cache, subscription-manager,
              : upgrade-helper, versionlock

**Comment by DaveRVos** [comment]
k/cryptography/hazmat/bindings/_openssl.abi3.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
        linux-vdso.so.1 =>  (0x00007ffdb329d000)
        /$LIB/liboneagentproc.so => /lib64/liboneagentproc.so (0x00007f615086e000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6150652000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f6150284000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6150f86000)
symbol getentropy, version GLIBC_2.25 not defined in file libc.so.6 with link time reference    (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: _Py_NoneStruct        (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyArg_UnpackTuple     (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyObject_CallMethod   (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openss^Coot@omlnlmon601 plugin_deployment]#(GLIBC_2.3) => /lib.so.64/ld-linux-x86-6sss
[root@omlnlmon601 plugin_deployment]# clear
[root@omlnlmon601 plugin_deployment]#  ldd -r -v /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so
ldd: warning: you do not have execution permission for `/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so'
/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
        linux-vdso.so.1 =>  (0x00007ffd3dbfe000)
        /$LIB/liboneagentproc.so => /lib64/liboneagentproc.so (0x00007fb551c91000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb551a75000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb5516a7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb5523a9000)
symbol getentropy, version GLIBC_2.25 not defined in file libc.so.6 with link time reference    (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: _Py_NoneStruct        (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyArg_UnpackTuple     (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyObject_CallMethod   (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyLong_FromVoidPtr    (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyLong_FromUnsignedLong       (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyErr_Occurred        (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
symbol getentropy, version GLIBC_2.25 not defined in file libc.so.6 with link time reference    (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyEval_RestoreThread  (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyEval_SaveThread     (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyObject_Malloc       (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyFloat_AsDouble      (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyLong_FromLong       (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: _Py_Dealloc   (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyObject_Free (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)
undefined symbol: PyImport_ImportModule (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)

        Version information:
        /opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so:
                libpthread.so.0 (GLIBC_2.2.5) => /lib64/libpthread.so.0
                libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.25) => not found
                libc.so.6 (GLIBC_2.7) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libpthread.so.0:
                ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.14) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2

**Comment by DaveRVos** [comment]
May be this has something to do with it: version GLIBC_2.25 not defined in file libc.so.6 with link time reference (/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.certcheck/cryptography/hazmat/bindings/_openssl.abi3.so)

**Comment by DaveRVos** [comment]
Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k
Release     : 24.el7_9
Size        : 814 k
Repo        : installed
From repo   : repo
Summary     : Utilities from the general purpose cryptography library with TLS
            : implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications
            : between machines. OpenSSL includes a certificate management tool
            : and shared libraries which provide various cryptographic
            : algorithms and protocols.

**Comment by DaveRVos** [comment]
Hi Reinhard, I can confirm that this version can be installed without errors. Thanks a lot

**Comment by PieterLuttig** [comment]
Hi Reinhard,

That's awesome, I can also confirm that it's working now, thanks a lot!

**Comment by DaveRVos** [comment]
Hi Reinhard and Pieter,
Although the installation went well, the creation of problems does not occur. I compared both the prod environment with REHL7.9 AG with my demo environment with RHEL8 and accessed the same URL. Only the later created a problem.

**Comment by DaveRVos** [comment]
![image](https://user-images.githubusercontent.com/115137686/194527763-d9a34efc-ce0c-4964-9f83-e0cd5e7e8c38.png)
![image](https://user-images.githubusercontent.com/115137686/194527892-13fe41b4-062d-4deb-bd4a-c3f2be639695.png)

**Comment by DaveRVos** [comment]
Does it work for you Pieter?

**Comment by DaveRVos** [comment]
I see the URLs are different but I tried with Google.com first with the same result.
