### ISSUE TITLE
Plugin only getting SSL info from one of the Synthetics  

### ISSUE THREAD

**Issue by Copeca1012** [360Performance/dynatrace-plugin-certcheck#23]
Hi , I just deployed the plugin and tagged some of the HTTP test I have i need the SSL Exp info , but the metric is only pulling the data from one of them even when splitting by hostname. Any idea would be greatly appreciate it .

![ssl1](https://user-images.githubusercontent.com/132359081/235662248-cff9332f-71a7-4f51-9aef-ccb0fc95c242.png)

**Comment by Copeca1012** [comment]
I think the issue is some of those URL are only accessible from local network and even when im using a private location for the tests the plugin is not seeing them. Any idea how could I get it to work for privates domains??

**Comment by Copeca1012** [comment]
Found out the issue , thanks a lot for your help . You are the best

**Comment by reinhard-brandstaedter** [comment]
Super, you're welcome!
