### ISSUE TITLE
Error(No module named '_cffi_backend')

### ISSUE THREAD

**Issue by heydenb** [360Performance/dynatrace-plugin-certcheck#4]
Dear,

I get following error when I want to use this plugin on my Linux AG.
I see that there is an "so" file included regarding cffi backend. Does that need to go somewhere?

Thanks,
Bert

**Comment by heydenb** [comment]
I rebuild the plugin with Python 3.8. Since that is the new version now. Not I get this error when the plugin loaded:
`Error(cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_TLSv1_3_FUNCTIONS')`

Maybe something changed in the cryptography module.

**Comment by jshuff27** [comment]
Same issue here. ActiveGates updated to 1.231.246 today which include Python 3.8.  Got this error right away, Error(No module named '_cffi_backend')

**Comment by heydenb** [comment]
I have build the plugin on an python 3.8 virtualenv and it works for me now. I added the package here so everyone can use it.
[custom.remote.python.certcheck.zip](https://github.com/360Performance/dynatrace-plugin-certcheck/files/7914997/custom.remote.python.certcheck.zip)

**Comment by reinhard-brandstaedter** [comment]
Thanks Bert! Awesome!

**Comment by heydenb** [comment]
And here is a version which was build on CentOs 7.9. The previous one complainted about a missing GLIBC_2.18.
[custom.remote.python.certcheck.zip](https://github.com/360Performance/dynatrace-plugin-certcheck/files/7933416/custom.remote.python.certcheck.zip)

**Comment by reinhard-brandstaedter** [comment]
@jshuff27 is this fixed for you with the latest release?

**Comment by jshuff27** [comment]
It sure is.  We actually had to give it a week before Dynatrace stopped flapping between 'OK' and 'Error on _cffi_backend'.   It was like even though i changed what AG to run on, DT was still trying to run it on the old ones. It was a DT issue, everything is stable now.
